name: fahrschul_manager
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  animations: ^2.0.11
  awesome_snackbar_content: ^0.1.3
  calendar_view: ^1.2.0

  flutter:
    sdk: flutter
  flutter_slidable: ^3.1.1
  parse_server_sdk_flutter: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
