name: fahrschul_manager
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  animations: ^2.0.11
  async_searchable_dropdown: ^0.0.7+4
  awesome_snackbar_content: ^0.1.1
  calendar_view: ^1.2.0
  flutter_form_bloc: ^0.31.0

  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_slidable: ^3.1.1
  logger: ^2.4.0
  package_info_plus: ^4.2.0
  parse_server_sdk_flutter: ^8.0.0
  loading_indicator: ^3.1.1
  animated_segmented_tab_control: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/Logo_neu.jpg
